### ISSUE TITLE
Fixing navbar scrolling effect color 

### ISSUE THREAD

**Issue by Davidohis** [zero-to-mastery/HTML-project#339]
Fixing navbar scrolling effect color

**Comment by skpandey885** [comment]
Hey Can I Work On It?

**Comment by Davidohis** [comment]
yes

**Comment by skpandey885** [comment]
Can You Assign This To Me?
and Tell Me What Exactly I Have To Do?

**Comment by l-white** [comment]
@skpandey885 You can just submit a pull request with the changes. We don't assign issues to people with this repo.
