### ISSUE TITLE
dropdown content not working on contributersProfile page

### ISSUE THREAD

**Issue by shreyshreyansh** [zero-to-mastery/HTML-project#373]
It just shows small blue bar on hover

![Screenshot 2021-07-28 101330](https://user-images.githubusercontent.com/53744971/127265157-2ce9d7f0-969a-4c1c-a993-2533ccda8d04.png)

**Comment by rishi-koul** [comment]
Hi, I looked into the issue the only reason I think it is showing a blue bar is because you currently don't have any dropdown items. 

```
<div class="dropDownContent">
      <a href="#">Link 1</a>
      <a href="#">Link 2</a>
      <a href="#">Link 3</a>
</div>
```
Add some items like this and then you will see the items

**Comment by cryptic-padawan** [comment]
I would like to work on this issue

**Comment by l-white** [comment]
This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
