### ISSUE TITLE
Chevron circle up icon on index doesn't show

### ISSUE THREAD

**Issue by Lejla1502** [zero-to-mastery/HTML-project#410]
Chevron circle up inside of a tag on index page does't work (show), nor does it link to anywhere

**Comment by l-white** [comment]
@Lejla1502 This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug or would like to add a new feature, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
