### ISSUE TITLE
Making the images of Circle shape with some more styling.

### ISSUE THREAD

**Issue by eshan1925** [zero-to-mastery/HTML-project#420]
![image](https://user-images.githubusercontent.com/78701779/149900744-479ea001-aa9b-445e-bd6a-e44ca008ebf5.png)

Hey,
So I want to contribute to this project and I was thinking to upgrade the styling of this page and I will try to make the images inside a circle. Somewhat like this.
![image](https://user-images.githubusercontent.com/78701779/149900975-ed2ba81c-edd0-46d4-913e-79aa50407525.png)
Because like this the website looks very cluttered. So may I work on this.
Please assign me this @maintainers @MattCSmith .

**Comment by l-white** [comment]
@eshan1925  This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug or would like to add a new feature, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
