### ISSUE TITLE
Nav bar options disappers or blends with the background color

### ISSUE THREAD

**Issue by manishbajagai2** [zero-to-mastery/HTML-project#422]
As we hover over the navbar option or even click on any one, it blends with the background. In Light Mode, option is coloured  white and in dark mode option is black. Therefore cant be seen when hovered over them. I would be happy to work on this but it needs to be fixed
@MattCSmith

**Comment by anayatkhan1** [comment]
hey @manishbajagai2 , can you send the screenshot and also tell them the section of source code

**Comment by l-white** [comment]
This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug or would like to add a new feature, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
