### ISSUE TITLE
duplicated navbar on beyondztm html page

### ISSUE THREAD

**Issue by victoriacheng15** [zero-to-mastery/HTML-project#426]
See screenshot here
![image](https://user-images.githubusercontent.com/35031228/153249848-11f5a23c-78ab-45a1-b523-de4b222acc08.png)

**Comment by Abhay2342** [comment]
I created a PR for this.

**Comment by victoriacheng15** [comment]
> I created a PR for this.

Can you link the PR?

**Comment by Abhay2342** [comment]
It got closed now. Should I edit it again and create a new PR?

**Comment by victoriacheng15** [comment]
> It got closed now. Should I edit it again and create a new PR?

I don't think you need to. And I was looking for it. 

This issue is resolved with #442
