### ISSUE TITLE
[Bug] Dark theme shows images in negative color

### ISSUE THREAD

**Issue by RaheemAmer** [zero-to-mastery/HTML-project#452]
## Preview of the bug :

![image](https://user-images.githubusercontent.com/18606136/190709007-430a3735-6bfb-4e6f-90a4-052eec21e8d8.png)

## This article can help
- https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by anayatkhan1** [comment]
Hey there, @RaheemAmer , i would like to work on this bug

**Comment by RaheemAmer** [comment]
@anayatkhan1 I'm not a repo maintainer to assign this issue to you, I'm just a normal member reporting this bug

**Comment by l-white** [comment]
This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug or would like to add a new feature, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
