### ISSUE TITLE
footer is placed at wrong place

### ISSUE THREAD

**Issue by yuvisingh01** [zero-to-mastery/HTML-project#466]
Please allow me to solve this issue, it would be my first open source contribution.

**Comment by pankajkrbansal** [comment]
Hey, I would like to work on it

**Comment by rohitchbju** [comment]
it looks interesting can i work on that

**Comment by l-white** [comment]
This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
