### ISSUE TITLE
Phone button is placed slightly higher than other buttons.

### ISSUE THREAD

**Issue by mjmanas54** [zero-to-mastery/HTML-project#467]
![Screenshot (81)](https://user-images.githubusercontent.com/101850957/194738809-8532d0ad-1475-4e53-a2fb-6399f2c36b2b.png)

as shown in above screenshot the phone button is placed slightly higher than other buttons.

**Comment by mjmanas54** [comment]
I would like to fix this issue please assign it to me.

**Comment by Saga-sanga** [comment]
I don't think you need to be assigned anything for this project. You can just make your fixes and make a pull request.

**Comment by mjmanas54** [comment]
Sir, I had fixed this issue and made PR[#468](https://github.com/zero-to-mastery/HTML-project/pull/468) please review it.
Thank you.
