### ISSUE TITLE
on todo_list page submit is show to big and simple 

### ISSUE THREAD

**Issue by Sneha-Mittal88293** [zero-to-mastery/HTML-project#474]
change the submit button size margin and padding and style on todo_list page

**Comment by Parth-2609** [comment]
hey can u assign this to me !!

**Comment by l-white** [comment]
This is a playground for students to experiment with HTML, CSS and JavaScript, so not everything will work properly. If you see a bug, please feel free to submit a pull request. We do not assign issues to contributors for this repository.
