### ISSUE TITLE
After hover the color of navbar text turns white. 

### ISSUE THREAD

**Issue by humsarika** [zero-to-mastery/HTML-project#476]
![image](https://user-images.githubusercontent.com/75199589/195680961-eb077825-4fae-41d2-b44b-308da887875e.png)

After hover, the color of the navbar text turns white. 
I want to contribute to this repo.
@zero-to-mastery can I work on this issue?

**Comment by Parth-2609** [comment]
Hey please assign this issue to me under the Hacktoberfest tag, I have good knowledge of how to solve this issue and can solve this in minimal time.

**Comment by humsarika** [comment]
@Parth-2609 hello parth , I'have already solved the issue under PR #477
