### ISSUE TITLE
want to enhance signup page

### ISSUE THREAD

**Issue by Developersubham18** [zero-to-mastery/HTML-project#482]
The current signup page is not looking good, I want to keep them inside a card for better user experience.

Kindly assign me this issue under hacktoberfest

**Comment by Anshika91** [comment]
please assign this task to me

**Comment by sarthaksharma27** [comment]
I just solved the problem and created a pull request Please review and merge it

**Comment by l-white** [comment]
Issues don't need to be opened for these -- you can submit a pull request. This is an experimental repo, so we don't assign tasks to students. If a pull request has been submitted for a feature you want to add, you can add another one or make additional changes. The best way to get a pull request confirmed is to submit one small change at a time but you can make multiple contributions if you wish. Big changes often have multiple merge conflicts, and if I see multiple files with issues, I typically close the PR and encourage the contributor to try again. I hope that helps. @sarthaksharma27 @Anshika91 @Developersubham18
