### ISSUE TITLE
Light Mode Toggle is not properly placed

### ISSUE THREAD

**Issue by Chinwenma** [zero-to-mastery/HTML-project#528]
Description:
The "light mode" toggle is going out of its box

To Reproduce
1. Go to the Homepage
2. check out the navigation menu 
3. toggle the light and dark mode 
Expected behavior
it should not go out of the box
screenshot
![Screenshot (52)](https://github.com/zero-to-mastery/HTML-project/assets/113705632/89f1a905-b199-45ed-bb46-5ad7b9099af2)
  I  fix this if it is assigned to me

**Comment by l-white** [comment]
@Chinwenma Looks like we already have a pull request with this change but thank you for your willingness to contribute to this repo.
