### ISSUE TITLE
Improvement in UI: improper alignment of icons

### ISSUE THREAD

**Issue by deveshidwivedi** [zero-to-mastery/HTML-project#543]
I could align the icons properly as currently, they are not in the most proper way.
Please assign this to me under hacktoberfest'23.

<img width="346" alt="Screenshot 2023-10-08 123017" src="https://github.com/zero-to-mastery/HTML-project/assets/120312681/36dc225a-1dce-4957-9ec1-17aeeeffa1dd">

**Comment by l-white** [comment]
@deveshidwivedi Please see README: We do not assign people to issues for this repo. It is a playground for you to practice. You are welcome to work on this issue, but please note also that this is not one of our repos that counts towards Hacktoberfest. For those repos, please look for the #hacktoberfest hash tag.
