### ISSUE TITLE
Update dark and light mode button

### ISSUE THREAD

**Issue by Swadeshit27** [zero-to-mastery/HTML-project#547]
The dark and light mode button is defective. Can i update this button ? Please assign me this issue.
![image](https://github.com/zero-to-mastery/HTML-project/assets/97722877/cb2f6bd0-16a8-4722-bda9-e801a4c9ba69)

**Comment by AnshuWorld** [comment]
i want to contribute here please assign me

**Comment by ahmedrazabaloch** [comment]
The dark and light mode button is defective i can fix that Please assign it to me.

**Comment by radhe098** [comment]
issue is solved I've sent PR if its applicable then merge it and close the issue.
